config/routes.rb
Rails.application.routes.draw do

root to: "public/homes#top"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    get 'homes/about'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :yakitoris, only: [:index, :new, :create, :show, :edit, :update]
    resources :yakitori_comments, only: [:index, :destroy]
  end


  namespace :public do
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get 'homes/top'
    get 'homes/about'
    resources :rooms, only: [:create,:show]
    resources :messages, only: [:create]

    resources :yakitoris, only: [:index, :show,] do
    resource :favorite, only: [:create, :destroy]
    resources :yakitori_comments, only: [:create, :destroy]
    
  end
    get 'customers/:id/favorites', to: 'customers#favorites', as: 'customers_favorites'
    get "customers/:id/mypage", to: "customers#show"
    get "customers/information/edit", to: "customers#edit"
    patch "customers/information", to: "customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"
  end

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :yakitori, dependent: :destroy
         has_many :yakitori_comments, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :yakitori_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorite_yakitoris, through: :favorites, source: :yakitori
  has_one_attached :profile_image

  def full_name
    "#{last_name} #{first_name}"
  end

  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_CUSTOMER_EMAIL) do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guestuser"
    end
  end
  
  def guest?
    email == "guest@example.com"
  end  
  
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :yakitori

  validates :customer_id, uniqueness: {scope: :yakitori_id}

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :yakitoris, dependent: :destroy
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :customer
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/yakitori.rb
class Yakitori < ApplicationRecord

  belongs_to :genre
  has_many :yakitori_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  #validates :comment, presence: true
  #品目の投稿が出来なくなる


  def self.looks(search, word)
    if search == "perfect_match"
      @yakitori = Yakitori.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @yakitori = Yakitori.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @yakitori = Yakitori.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @yakitori = Yakitori.where("name LIKE?","%#{word}%")
    else
      @yakitori = Yakitori.all
    end
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/models/yakitori_comment.rb
class YakitoriComment < ApplicationRecord
  
  belongs_to :customer
  belongs_to :yakitori
  
  validates :comment, presence: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


private

  def genre_params
     params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/yakitoris_controller.rb
class Admin::YakitorisController < ApplicationController
  before_action :authenticate_admin!

  def index
    @yakitoris = Yakitori.all
  end

  def new
    @yakitori = Yakitori.new
  end

  def create
      @yakitori = Yakitori.new(yakitori_params)
    if @yakitori.save
      flash[:notice] = "焼き鳥の新規登録が完了しました"
      redirect_to admin_yakitori_path(@yakitori.id)
    else
      render 'new'
    end
  end

  def show
    @yakitori = Yakitori.find(params[:id])
  end

  def edit
    @yakitori = Yakitori.find(params[:id])
  end

  def update
    @yakitori = Yakitori.find(params[:id])
    if @yakitori.update(yakitori_params)
      flash[:notice] = "焼き鳥の詳細変更が完了しました。"
      redirect_to admin_yakitori_path
    else
      flash[:notice] = "焼き鳥の詳細変更に失敗しました。"
      render :edit
    end
  end
end


private

  def yakitori_params
    params.require(:yakitori).permit(:image, :name, :introduction, :genre_id,)
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end

  def after_sign_out_path_for(resource)
    admin_homes_top_path
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/yakitoris_helper.rb
module Admin::YakitorisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/yakitori_comments_helper.rb
module YakitoriCommentsHelper
end

app/views/admin/yakitoris/edit.html.erb
<div class="container">
  <div class="row my-3 offset-1 text-center">
    <h2>焼き鳥編集</h2>
  </div>

  <div class="row">
    <div class="col">
      <%= form_with model: @yakitori, url: admin_yakitori_path,method: :patch do |f| %>
        <form class="form-horizontal ">

          <div class="form-group row">
            <%= f.label :焼き鳥画像,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.file_field :image, accept: "image/*",class:"form-control-file"  %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :焼き鳥の名前,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :焼き鳥の説明,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.text_area :introduction,class:"form-control" %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :ジャンル,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--",class:"form-select" %>
            </div>
          </div>

          <div class="text-center my-3">
            <%= f.submit "変更を保存", class:"btn btn-success" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/yakitoris/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>品目一覧</h2>
      <h3><%= link_to "コメント一覧", admin_yakitori_comments_path %></h3>
    </div>
      <div class="col-sm-2 px-sm-0 text-right mt-3">
        <%= link_to new_admin_yakitori_path do %>
        <button type="button" class="btn btn-light rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
        <% end %>
      </div>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>品目ID</th>
          <th>品目</th>
          <th>ジャンル</th>
        </tr>
      </thead>
      <tbody>
        <% @yakitoris.each do |yakitori| %>
          <tr>
           <% if yakitori.image.attached? %>
                  <td><%= image_tag yakitori.image, size: '250x200' %></td>
                <% else %>
                  <td><%= image_tag 'no_image', size: "250x200" %></td>
                <% end %>
            <td><%= yakitori.id %></td>
            <td><%= link_to yakitori.name, admin_yakitori_path(yakitori.id) %></td>
            <td><%= yakitori.genre.name %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/yakitoris/new.html.erb
<div class="container">
  <div class="row my-3 offset-1 text-center">
    <h2>品目新規登録</h2>
  </div>
  <div class="row">
　  <div class="col">
      <%= form_with model: @yakitori, url: admin_yakitoris_path, method: :post, local: true do |f| %>
        <form class="form-horizontal">
          <div class="form-group row">
            <%= f.label :品目画像,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.file_field :image, accept: "image/*",class:"form-control-file"  %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :品目名,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :品目説明,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.text_area :introduction,class:"form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :ジャンル,class:"col-sm-2 control-label" %>
            <div class="col-sm-5">
              <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--",class:"form-select" %>
            </div>
          </div>
          <div class="text-center my-3">
            <%= f.submit "新規登録", class:"btn btn-success" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/yakitoris/show.html.erb
<div class="container">
  <div class="row mt-3 mb-3 offset-1 text-center">
    <h2>焼き鳥の詳細</h2>
  </div>

  <div class="row">
    <div class="col-md-3">
      <% if @yakitori.image.attached? %>
        <%= image_tag @yakitori.image, size: '250x200' %>
      <% else %>
        <%= image_tag 'no_image', size: "250x200" %>
      <% end %>
    </div>

    <div class="col-md-6 item-details mx-auto">
      <table class="table">
        <tr>
          <th>焼き鳥の名前</th>
          <th><%= @yakitori.name %></th>
        </tr>
        <tr>
          <th>焼き鳥の説明</th>
          <th><%= @yakitori.introduction %></th>
        </tr>
        <tr>
          <th>ジャンル</th>
          <th><%= @yakitori.genre.name %></th>
        </tr>
      </table>

    <div>
    <%=link_to "編集する",edit_admin_yakitori_path, class:"btn btn-success mb-5" %>
    </div>

    </div>
  </div>
</div>