config/routes.rb
Rails.application.routes.draw do

root to: "public/homes#top"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    get 'homes/about'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :yakitoris, only: [:index, :new, :create, :show, :edit, :update]
    resources :yakitori_comments, only: [:index, :destroy]
  end


  namespace :public do
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get 'homes/top'
    get 'homes/about'
    resources :rooms, only: [:create,:show]
    resources :messages, only: [:create]

    resources :yakitoris, only: [:index, :show,] do
    resource :favorite, only: [:create, :destroy]
    resources :yakitori_comments, only: [:create, :destroy]
    
  end
    get 'customers/:id/favorites', to: 'customers#favorites', as: 'customers_favorites'
    get "customers/:id/mypage", to: "customers#show"
    get "customers/information/edit", to: "customers#edit"
    patch "customers/information", to: "customers#update"
    get 'customers/unsubscribe', to: "customers#unsubscribe"
    patch 'customers/withdraw', to: "customers#withdraw"
  end

  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :yakitori, dependent: :destroy
         has_many :yakitori_comments, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :yakitori_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorite_yakitoris, through: :favorites, source: :yakitori
  has_one_attached :profile_image

  def full_name
    "#{last_name} #{first_name}"
  end

  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_CUSTOMER_EMAIL) do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.last_name = "guestuser"
    end
  end
  
  def guest?
    email == "guest@example.com"
  end  
  
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :yakitori

  validates :customer_id, uniqueness: {scope: :yakitori_id}

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :yakitoris, dependent: :destroy
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer
  belongs_to :room
  
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :customer
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/yakitori.rb
class Yakitori < ApplicationRecord

  belongs_to :genre
  has_many :yakitori_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  #validates :comment, presence: true
  #品目の投稿が出来なくなる


  def self.looks(search, word)
    if search == "perfect_match"
      @yakitori = Yakitori.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @yakitori = Yakitori.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @yakitori = Yakitori.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @yakitori = Yakitori.where("name LIKE?","%#{word}%")
    else
      @yakitori = Yakitori.all
    end
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/models/yakitori_comment.rb
class YakitoriComment < ApplicationRecord
  
  belongs_to :customer
  belongs_to :yakitori
  
  validates :comment, presence: true
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  
  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end

  def after_sign_out_path_for(resource)
    admin_homes_top_path
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/yakitoris_helper.rb
module Admin::YakitorisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/yakitori_comments_helper.rb
module YakitoriCommentsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<!--管理者ログイン時ー-->
<% if admin_signed_in? %>
<div class="container">
  <div class="row">
    <li class="nav-item ">
      <%= link_to admin_customers_path do %>
        <h4 class="fa-solid text-dark fa-user">会員一覧</h4>
      <% end %>
    </li>
    <li class="nav-item ">
      <%= link_to admin_yakitoris_path do %>
        <h4 class="fa-solid text-dark fa-crow">焼き鳥一覧</h4>
      <% end %>
    </li>
    <li class="nav-item ">
      <%= link_to admin_genres_path do%>
        <h4 class="fa-solid text-dark fa-database">ジャンル一覧</h4>
      <% end %>
    </li>
    <li class="nav-item ">
      <%= link_to destroy_admin_session_path, method: :delete do %>
        <h4 class="fa-solid text-dark fa-user">ログアウト</h4>
      <% end %>
    </li>
  </div>
</div>
<!--ログインした時ー-->
<% elsif customer_signed_in? %>
<div class="container">
  <div class="row">
    <li class="search_form">
      <%= form_with url: public_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select( [['焼き鳥']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
    </li>
    <h4 class="nav-item">
      <%= link_to public_path(current_customer) do %>
        <i class="fa-solid text-dark fa-user">マイページ</i>
      <% end %>
    </h4>
    <h4 class="nav-item">
      <%= link_to  public_yakitoris_path do %>
        <i class="fa-solid text-dark fa-crow">焼き鳥一覧</i>
      <% end %>
    </h4>
    <h4 class="nav-item">
      <%= link_to destroy_customer_session_path, method: :delete do %>
        <i class="fa-solid text-dark fa-user">ログアウト</i>
      <% end %>
    </h4>
  </div>
</div>
        <!--ログインしてないー-->
        <% else %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" =>一覧画面</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/public/homes/top">TOP<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/public/homes/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/customers/sign_up">新規会員登録</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/customers/sign_in">ログイン</a>
        </li>
        <li class="nav-item">
          <%= link_to  customers_guest_sign_in_path, method: :post do%>
        <i class="fa-solid text-dark fa-user">ゲストログイン</i>
      <% end %>
        </li>
      </ul>
  </div>
</nav>
<% end %>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: gray;">
  <a class="navbar-brand mx-5 img-thumbnail" href="/public/homes/top"><%= image_tag "ROGO3.png", :size => "70x70" %></a>
  <h1 class="text-center",class="text-font">Grill Bird</h1>
    <div class="collapse navbar-collapse flex-column">
      <ul class="nav ml-auto mx-5">
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grillbird</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0e1ec59f06.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
</html>
<body class="d-flex flex-column">
    <%= render 'layouts/header' %>
  <main class="flex-grow-1">
   <%= yield %>
  </main>
    <div style="background-color: gray;">
      <div class="container">
        <div class="row">
          <div class="col">
            <h1 class="text-center">Yakitori</h1>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>